package com.example.pickmeup.httpServices;

import androidx.annotation.Nullable;

import com.android.volley.VolleyError;


/**
 * This is an abstract class that can be used for callbacks in volley requests. Methods can be overridden to for handling the Volley Request's response/error.
 * These methods will be called when Volley's Request has received a response/error.
 */
public abstract class VolleyCallback {
    /**
     * This method functions like String Request's onResponse() method .
     * @param response String response from Volley Request
     */
    public void onSuccessResponse(String response){

    } //returns string response from volley request

    /**
     *  This method will return a parsed int and substring taken from Volley Request's response.
     * @param intResponse An int parsed from OnSuccess's response
     * @param subString returns a substring taken from OnResponse
     */
    public void onSuccessResponse(int intResponse, @Nullable String subString){

    }//returns an int and substring if there is one


    /**
     * This method will return an error provided by the Volley Request and a custom string generated by the caller.
     * @param error VolleyError as returned by Volley's String Request
     * @param message Custom generated String that may be used for notifying for a user about the Volley Error
     */
    public abstract void onErrorResponse(VolleyError error, String message); //returns VolleyError and an associated message
}
